/**
 * @hive-flow/api — GraphQL operations and utility types for HiveFlow.
 * All queries and mutations are gql document nodes compatible with @apollo/client.
 */

export type Maybe<T> = T | null;

export {
  GET_PROJECTS,
  GET_PROJECT,
  CREATE_PROJECT,
  UPDATE_PROJECT,
  DELETE_PROJECT,
  UPDATE_PROJECT_TASK,
  CREATE_PROJECT_TASK,
  DELETE_PROJECT_TASK,
  CREATE_PROJECT_TASK_DEPENDENCY,
  DELETE_PROJECT_TASK_DEPENDENCY,
  UPDATE_PROJECT_TASK_TIMELINE_ORDER,
} from '../graphql/projects';

export {
  GET_EQUIPMENT,
  CREATE_EQUIPMENT,
  UPDATE_EQUIPMENT,
  DELETE_EQUIPMENT,
} from '../graphql/equipment';

export {
  GET_ESTIMATES,
  GET_ESTIMATE_SINGLE,
  CREATE_ESTIMATE,
  UPDATE_ESTIMATE,
  DELETE_ESTIMATE,
  UPDATE_ESTIMATE_TASK,
  CREATE_ESTIMATE_TASK,
  DELETE_ESTIMATE_TASK,
  CREATE_ESTIMATE_TASK_DEPENDENCY,
  DELETE_ESTIMATE_TASK_DEPENDENCY,
  CREATE_ESTIMATE_LINE_ITEM,
  UPDATE_ESTIMATE_LINE_ITEM,
  DELETE_ESTIMATE_LINE_ITEM,
  UPDATE_ESTIMATE_TASK_TIMELINE_ORDER,
} from '../graphql/estimates';

export {
  GET_PROJECT_FILES,
  CREATE_PROJECT_FOLDER,
  MOVE_PROJECT_FILE,
  DELETE_PROJECT_FILE,
  RENAME_PROJECT_FILE,
  UPLOAD_PROJECT_FILES,
} from '../graphql/files';

export {
  GET_TIMELINES,
  GET_TIMELINE_DATA,
  GET_PROJECT_INFO,
  CREATE_TIMELINE,
  CREATE_TIMELINE_ITEM,
  DELETE_TIMELINE_ITEM,
  UPDATE_TIMELINE_ITEM,
  UPDATE_TIMELINE_ITEM_ORDER,
  CREATE_TIMELINE_ITEM_DEPENDENCY,
  DELETE_TIMELINE_ITEM_DEPENDENCY,
} from '../graphql/timeline';
